In [14]:
import numpy as np
from sklearn.model_selection import train_test_split

In [15]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
y = np.array([5,10,15,20,25,30,35,40,45,50])

In [16]:
print(x)
print(x.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [17]:
print(y)
print(y.shape)

[ 5 10 15 20 25 30 35 40 45 50]
(10,)


In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8)

In [19]:
print(x_train)
print(x_test)

[ 8  6  9  7  1 10  3  2]
[5 4]


In [22]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,shuffle=False)

In [23]:
print(x_train)
print(x_test)

[1 2 3 4 5 6 7 8]
[ 9 10]


In [25]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,shuffle=True,random_state=2)

In [26]:
print(x_train)
print(x_test)

[ 6  1  8  3  4  7 10  9]
[5 2]
