**Scratch Code MAE,MSE,RMSE**







In [42]:
import numpy as np

In [43]:
ac = np.array([10, 20, 30, 40, 50])
pr = np.array([11, 18, 33, 45, 47])

In [44]:
print(ac)

[10 20 30 40 50]


In [45]:
print(pr)

[11 18 33 45 47]


In [46]:
dif = ac - pr

In [47]:
print(dif)

[-1  2 -3 -5  3]


**MAE**

In [48]:
x = abs(dif)
print(x)

[1 2 3 5 3]


In [49]:
mae = np.mean(x)
print(mae)

2.8


**MSE**

In [50]:
s = np.square(dif)

In [51]:
print(s)

[ 1  4  9 25  9]


In [52]:
mse = np.mean(s)
print(mse)

9.6


**RMSE**

In [53]:
rmse = np.square(mse)
print(rmse)

92.16


**Using Library**

**MAE**

In [54]:
from sklearn.metrics import mean_absolute_error

In [55]:
y_true = [10, 20, 30, 40, 50]
y_pred = [11, 18, 33, 45, 47]

In [56]:
MAE = mean_absolute_error(y_true, y_pred)
print(MAE)

2.8


**MSE**

In [57]:
from sklearn.metrics import mean_squared_error

In [58]:
mse = mean_squared_error(y_true, y_pred)
print(mse)

9.6


**RMSE**

In [59]:
from sklearn.metrics import mean_squared_error

In [60]:
rmse = mean_squared_error(y_true, y_pred, squared = False)
print(rmse)

3.0983866769659336


**CROSS ENTROPY LOG LOSS**

In [61]:
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))
 
'''
yHat represents the predicted value / probability value calculated as output of hypothesis / sigmoid function
 
y represents the actual label
'''
def cross_entropy_loss(yHat, y):
    if y == 1:
      return -np.log(yHat)
    else:
      return -np.log(1 - yHat)

In [62]:
# Calculate sample values for Z
z = np.arange(-10, 10, 0.1)
# Calculate the hypothesis value / probability value
h_z = sigmoid(z)
# Value of cost function when y = 1
# -log(h(x))
cost_1 = cross_entropy_loss(h_z, 1)
# Value of cost function when y = 0
# -log(1 - h(x))
cost_0 = cross_entropy_loss(h_z, 0)

In [63]:
print(cost_1)

[1.00000454e+01 9.90005017e+00 9.80005545e+00 9.70006128e+00
 9.60006773e+00 9.50007485e+00 9.40008272e+00 9.30009142e+00
 9.20010103e+00 9.10011166e+00 9.00012340e+00 8.90013638e+00
 8.80015072e+00 8.70016657e+00 8.60018409e+00 8.50020345e+00
 8.40022484e+00 8.30024849e+00 8.20027462e+00 8.10030349e+00
 8.00033541e+00 7.90037067e+00 7.80040965e+00 7.70045272e+00
 7.60050033e+00 7.50055293e+00 7.40061107e+00 7.30067531e+00
 7.20074631e+00 7.10082476e+00 7.00091147e+00 6.90100728e+00
 6.80111316e+00 6.70123015e+00 6.60135944e+00 6.50150231e+00
 6.40166018e+00 6.30183462e+00 6.20202737e+00 6.10224036e+00
 6.00247569e+00 5.90273570e+00 5.80302298e+00 5.70334038e+00
 5.60369104e+00 5.50407844e+00 5.40450641e+00 5.30497918e+00
 5.20550140e+00 5.10607824e+00 5.00671535e+00 4.90741899e+00
 4.80819607e+00 4.70905416e+00 4.61000165e+00 4.51104774e+00
 4.41220258e+00 4.31347733e+00 4.21488425e+00 4.11643685e+00
 4.01814993e+00 3.92003977e+00 3.82212422e+00 3.72442285e+00
 3.62695709e+00 3.529750

In [64]:
print(cost_0)

[4.53988992e-05 5.01734233e-05 5.54500620e-05 6.12816173e-05
 6.77264430e-05 7.48490286e-05 8.27206441e-05 9.14200525e-05
 1.01034298e-04 1.11659574e-04 1.23402190e-04 1.36379626e-04
 1.50721716e-04 1.66571937e-04 1.84088848e-04 2.03447672e-04
 2.24842045e-04 2.48485952e-04 2.74615860e-04 3.03493079e-04
 3.35406373e-04 3.70674832e-04 4.09651061e-04 4.52724688e-04
 5.00326249e-04 5.52931475e-04 6.11066022e-04 6.75310702e-04
 7.46307252e-04 8.24764711e-04 9.11466454e-04 1.00727795e-03
 1.11315536e-03 1.23015495e-03 1.35944358e-03 1.50231016e-03
 1.66017841e-03 1.83462083e-03 2.02737412e-03 2.24035625e-03
 2.47568514e-03 2.73569938e-03 3.02298093e-03 3.34038017e-03
 3.69104343e-03 4.07844327e-03 4.50641180e-03 4.97917720e-03
 5.50140391e-03 6.07823660e-03 6.71534849e-03 7.41899415e-03
 8.19606734e-03 9.05416417e-03 1.00016521e-02 1.10477448e-02
 1.22025846e-02 1.34773304e-02 1.48842547e-02 1.64368473e-02
 1.81499279e-02 2.00397673e-02 2.21242165e-02 2.44228459e-02
 2.69570930e-02 2.975041

In [65]:
print(h_z)

[4.53978687e-05 5.01721647e-05 5.54485247e-05 6.12797396e-05
 6.77241496e-05 7.48462275e-05 8.27172229e-05 9.14158739e-05
 1.01029194e-04 1.11653341e-04 1.23394576e-04 1.36370327e-04
 1.50710358e-04 1.66558065e-04 1.84071905e-04 2.03426978e-04
 2.24816770e-04 2.48455082e-04 2.74578156e-04 3.03447030e-04
 3.35350130e-04 3.70606141e-04 4.09567165e-04 4.52622223e-04
 5.00201107e-04 5.52778637e-04 6.10879359e-04 6.75082731e-04
 7.46028834e-04 8.24424686e-04 9.11051194e-04 1.00677082e-03
 1.11253603e-03 1.22939862e-03 1.35851995e-03 1.50118226e-03
 1.65880108e-03 1.83293894e-03 2.02532039e-03 2.23784852e-03
 2.47262316e-03 2.73196076e-03 3.01841632e-03 3.33480731e-03
 3.68423990e-03 4.07013772e-03 4.49627316e-03 4.96680165e-03
 5.48629890e-03 6.05980149e-03 6.69285092e-03 7.39154134e-03
 8.16257115e-03 9.01329865e-03 9.95180187e-03 1.09869426e-02
 1.21284350e-02 1.33869178e-02 1.47740317e-02 1.63024994e-02
 1.79862100e-02 1.98403057e-02 2.18812709e-02 2.41270214e-02
 2.65969936e-02 2.931223